export enum SESchedule {
  WORKDAYS = 1,
  EVENING = 2,
  WEEKEND = 3,
}

export const SE_SCHEDULE_VALUES = Object.values(SESchedule) as number[]

export enum SECategory {
  REKL = 'REKL',
  CLEANING = 'CLEANING',
  CONSTRUCTION = 'CONSTRUCTION',
  DESIGN = 'DESIGN',
  PAINT = 'PAINT',
  PLUMBING = 'PLUMBING',
  ELECTRIC = 'ELECTRIC',
  GARDEN = 'GARDEN',
  HAIR = 'HAIR',
  HEALTH = 'HEALTH',
  NAILS = 'NAILS',
  TRANSPORT = 'TRANSPORT',
  PETS = 'PETS',
  PSYCHOLOGY = 'PSYCHOLOGY',
  PHOTO_VIDEO = 'PHOTO_VIDEO',
  BEAUTY = 'BEAUTY',
  COOK = 'COOK',
  SEW = 'SEW',
  CAR = 'CAR',
  CARE = 'CARE',
  EDUCATION = 'EDUCATION',
  REPAIR = 'REPAIR',
  IT = 'IT',
  ACCOUNTING = 'ACCOUNTING',
  MASSAGE = 'MASSAGE',
  COACH = 'COACH',
  TRANSLATION = 'TRANSLATION',
  LEGAL = 'LEGAL',
  OTHER = 'OTHER',
}

export const SE_CATEGORY_VALUES = Object.values(SECategory)
