export const seRegionMap = {
  1: 'Hela Stockholms län',
  2: 'Stockholm (innerstad)',
  10: 'Botkyrka',
  11: 'Danderyd',
  12: 'Ekerö',
  13: 'Haninge',
  14: 'Huddinge',
  15: 'Järfälla',
  16: 'Lidingö',
  17: 'Nacka',
  18: 'Norrtälje',
  19: 'Nykvarn',
  20: 'Nynäshamn',
  21: 'Salem',
  22: 'Sigtuna',
  23: 'Sollentuna',
  24: 'Solna',
  25: 'Sundbyberg',
  26: 'Södertälje',
  27: 'Tyresö',
  28: 'Täby',
  29: 'Upplands-Bro',
  30: 'Upplands Väsby',
  31: 'Vallentuna',
  32: 'Vaxholm',
  33: 'Värmdö',
  34: 'Österåker',
}

export const SE_REGION_VALUES = Object.keys(seRegionMap).map(r => Number(r))
